export const heroContent = {
  title: "Stranger Things",
  overview: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back. Set in the 1980s in the fictional town of Hawkins, Indiana, the first season focuses on the investigation into the disappearance of Will Byers.",
  backdropUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=1280&h=720"
};

export const trendingContent = [
  { 
    id: 1, 
    title: "The Crown", 
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "This drama follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    year: 2016,
    maturityRating: "16+",
    duration: "60m",
    genres: ["Historical Drama", "Political", "British"],
    match: 98
  },
  { 
    id: 2, 
    title: "Money Heist", 
    image: "https://images.unsplash.com/photo-1618022525341-874b48954af1?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
    year: 2017,
    maturityRating: "18+",
    duration: "50m",
    genres: ["Crime", "Thriller", "Spanish"],
    match: 95
  },
  { id: 3, title: "Dark", image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the dark secrets of four families.",
    year: 2017,
    maturityRating: "16+",
    duration: "60m",
    genres: ["Sci-Fi", "Thriller", "Mystery"],
    match: 92
  },
  { id: 4, title: "Breaking Bad", image: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    year: 2008,
    maturityRating: "18+",
    duration: "49m",
    genres: ["Crime", "Drama", "Thriller"],
    match: 90
  },
  { id: 5, title: "The Witcher", image: "https://images.unsplash.com/photo-1518709414768-a88981a4515d?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    year: 2019,
    maturityRating: "18+",
    duration: "60m",
    genres: ["Fantasy", "Action", "Adventure"],
    match: 88
  },
  { id: 6, title: "Ozark", image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.",
    year: 2017,
    maturityRating: "18+",
    duration: "60m",
    genres: ["Crime", "Drama", "Thriller"],
    match: 85
  },
  { id: 7, title: "Stranger Things", image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits. As they search for answers, the children unravel a series of extraordinary mysteries.",
    year: 2016,
    maturityRating: "16+",
    duration: "51m",
    genres: ["Sci-Fi", "Drama", "Horror"],
    match: 94
  },
  { id: 8, title: "Narcos", image: "https://images.unsplash.com/photo-1605806616949-1e87b487fc2f?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A chronicled look at the lucrative drug cartels of Colombia.",
    year: 2015,
    maturityRating: "18+",
    duration: "49m",
    genres: ["Crime", "Drama", "Thriller"],
    match: 82
  }
];

export const popularContent = [
  { 
    id: 9, 
    title: "The Queen's Gambit", 
    image: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.",
    year: 2020,
    maturityRating: "16+",
    duration: "60m",
    genres: ["Drama", "Historical", "Chess"],
    match: 97
  },
  { id: 10, title: "Peaky Blinders", image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
    year: 2013,
    maturityRating: "18+",
    duration: "60m",
    genres: ["Crime", "Drama"],
    match: 93
  },
  { id: 11, title: "Black Mirror", image: "https://images.unsplash.com/photo-1601974915431-3f6d742892c5?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    year: 2011,
    maturityRating: "18+",
    duration: "44m",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    match: 89
  },
  { id: 12, title: "Mindhunter", image: "https://images.unsplash.com/photo-1596727147705-61a532a659bd?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.",
    year: 2017,
    maturityRating: "18+",
    duration: "50m",
    genres: ["Crime", "Drama", "Thriller"],
    match: 86
  },
  { id: 13, title: "The Last Kingdom", image: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "As Alfred the Great defends his kingdom from Norse invaders, Uhtred—born a Saxon but raised by Vikings—claims his ancestral birthright.",
    year: 2015,
    maturityRating: "18+",
    duration: "60m",
    genres: ["Action", "Historical", "Drama"],
    match: 84
  },
  { id: 14, title: "You", image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.",
    year: 2018,
    maturityRating: "18+",
    duration: "45m",
    genres: ["Crime", "Drama", "Thriller"],
    match: 81
  },
  { id: 15, title: "Better Call Saul", image: "https://images.unsplash.com/photo-1569701813229-33284b643e3c?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the time before he established his strip-mall law office in Albuquerque, New Mexico as Saul Goodman.",
    year: 2015,
    maturityRating: "16+",
    duration: "46m",
    genres: ["Crime", "Drama", "Comedy"],
    match: 91
  },
  { id: 16, title: "The Umbrella Academy", image: "https://images.unsplash.com/photo-1590418606746-018840f9cd0f?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A family of former child heroes, now grown apart, must reunite to continue to protect the world.",
    year: 2019,
    maturityRating: "16+",
    duration: "60m",
    genres: ["Action", "Sci-Fi", "Comedy"],
    match: 87
  }
];

export const originals = [
  { id: 17, title: "Bridgerton", image: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Rich and lustful, Regency-era siblings navigate London high society's marriage mart, hoping to wed for love.",
    year: 2020,
    maturityRating: "16+",
    duration: "60m",
    genres: ["Drama", "Romance", "Historical"],
    match: 83
  },
  { id: 18, title: "The Haunting of Hill House", image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.",
    year: 2018,
    maturityRating: "18+",
    duration: "57m",
    genres: ["Horror", "Drama", "Mystery"],
    match: 79
  },
  { id: 19, title: "Cobra Kai", image: "https://images.unsplash.com/photo-1555597673-b21d5c935865?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again.",
    year: 2018,
    maturityRating: "13+",
    duration: "30m",
    genres: ["Action", "Comedy", "Drama"],
    match: 85
  },
  { id: 20, title: "Sex Education", image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic at school.",
    year: 2019,
    maturityRating: "18+",
    duration: "50m",
    genres: ["Comedy", "Drama"],
    match: 88
  },
  { id: 21, title: "The Irishman", image: "https://images.unsplash.com/photo-1520176501380-9a5274a98f60?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "An aging hitman recalls his time with the mob and the events that involved the disappearance of his longtime friend, Jimmy Hoffa.",
    year: 2019,
    maturityRating: "18+",
    duration: "209m",
    genres: ["Crime", "Drama"],
    match: 76
  },
  { id: 22, title: "Extraction", image: "https://images.unsplash.com/photo-1571501679680-de32f1e7aad4?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A black-market mercenary who has nothing to lose is hired to rescue the kidnapped son of an imprisoned international crime lord.",
    year: 2020,
    maturityRating: "18+",
    duration: "116m",
    genres: ["Action", "Thriller"],
    match: 72
  },
  { id: 23, title: "Bird Box", image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.",
    year: 2018,
    maturityRating: "18+",
    duration: "124m",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    match: 78
  },
  { id: 24, title: "Marriage Story", image: "https://images.unsplash.com/photo-1518199266791-5375a83bf0ad?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together.",
    year: 2019,
    maturityRating: "16+",
    duration: "136m",
    genres: ["Drama", "Romance"],
    match: 80
  }
];

export const documentaries = [
  { id: 25, title: "The Social Dilemma", image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.",
    year: 2020,
    maturityRating: "13+",
    duration: "94m",
    genres: ["Documentary"],
    match: 89
  },
  { id: 26, title: "Tiger King", image: "https://images.unsplash.com/photo-1577255714682-69db9b067fda?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "An exploration of big cat breeding and its bizarre underworld, populated by eccentric characters.",
    year: 2020,
    maturityRating: "18+",
    duration: "45m",
    genres: ["Documentary", "Crime"],
    match: 75
  },
  { id: 27, title: "Our Planet", image: "https://images.unsplash.com/photo-1552799446-159ba9523315?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Experience our planet's natural beauty and examine how climate change impacts all living creatures in this ambitious documentary.",
    year: 2019,
    maturityRating: "7+",
    duration: "50m",
    genres: ["Documentary", "Nature"],
    match: 92
  },
  { id: 28, title: "Making a Murderer", image: "https://images.unsplash.com/photo-1608512532576-1d5e26afacfd?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Filmed over 10 years, this real-life thriller follows what happens when a man wrongfully convicted of a crime is freed, only to become a suspect in a new crime.",
    year: 2015,
    maturityRating: "18+",
    duration: "60m",
    genres: ["Documentary", "Crime"],
    match: 81
  },
  { id: 29, title: "Formula 1: Drive to Survive", image: "https://images.unsplash.com/photo-1503945438517-f65904a52ce6?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "Drivers, managers and team owners live life in the fast lane -- both on and off the track -- during one cutthroat season of Formula 1 racing.",
    year: 2019,
    maturityRating: "13+",
    duration: "40m",
    genres: ["Documentary", "Sports"],
    match: 86
  },
  { id: 30, title: "Chef's Table", image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "In this Emmy-nominated series, meet innovative chefs from around the world who are redefining gourmet food with passion and creativity.",
    year: 2015,
    maturityRating: "7+",
    duration: "50m",
    genres: ["Documentary", "Food"],
    match: 88
  },
  { id: 31, title: "Night on Earth", image: "https://images.unsplash.com/photo-1498969866531-c739f584a9d9?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "This nature series employs cutting-edge technology to capture animals' nocturnal lives, revealing never-before-seen behaviors.",
    year: 2020,
    maturityRating: "7+",
    duration: "50m",
    genres: ["Documentary", "Nature"],
    match: 90
  },
  { id: 32, title: "The Last Dance", image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=300&h=200",
    description: "A 10-part documentary series about Michael Jordan and the Chicago Bulls' dynasty in the 1990s, featuring never-before-seen footage from the 1997-98 season.",
    year: 2020,
    maturityRating: "13+",
    duration: "50m",
    genres: ["Documentary", "Sports"],
    match: 94
  }
];
